definitions:
  users.FindResponse:
    properties:
      users:
        items:
          $ref: '#/definitions/users.User'
        type: array
    type: object
  users.User:
    properties:
      active:
        type: boolean
      createdAt:
        type: string
      deletedAt:
        type: string
      email:
        type: string
      firstName:
        type: string
      id:
        type: integer
      lastName:
        type: string
      password:
        type: string
      phone:
        type: string
      updatedAt:
        type: string
      username:
        type: string
      verifiedEmail:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /api/users:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users.FindResponse'
      summary: GetUsers
      tags:
      - Users
swagger: "2.0"
